version: '3.4'

services:
  msp_demo.api:
    image: mspdemoapi
    build:
      context: .
      dockerfile: MSP_Demo.Api/Dockerfile
    depends_on:
      - nosql.server

  nosql.server:
    image: mongo